spring:
  datasource:
    url: jdbc:mysql://192.168.1.233/taskdb
    username: root
    password: password
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
admin:
  prefix:
    uri: admin